//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: room.proto
namespace com.sansanbbox.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExistRoomWebRequest")]
  public partial class ExistRoomWebRequest : global::ProtoBuf.IExtensible
  {
    public ExistRoomWebRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExistRoomWebResponse")]
  public partial class ExistRoomWebResponse : global::ProtoBuf.IExtensible
  {
    public ExistRoomWebResponse() {}
    
    private bool _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientRegisterRequest")]
  public partial class ClientRegisterRequest : global::ProtoBuf.IExtensible
  {
    public ClientRegisterRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerRegisterResponse")]
  public partial class ServerRegisterResponse : global::ProtoBuf.IExtensible
  {
    public ServerRegisterResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientHeartBeatRequest")]
  public partial class ClientHeartBeatRequest : global::ProtoBuf.IExtensible
  {
    public ClientHeartBeatRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerHeartbeatResponse")]
  public partial class ServerHeartbeatResponse : global::ProtoBuf.IExtensible
  {
    public ServerHeartbeatResponse() {}
    
    private string _date_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"date_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string date_time
    {
      get { return _date_time; }
      set { _date_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomRequest")]
  public partial class EnterRoomRequest : global::ProtoBuf.IExtensible
  {
    public EnterRoomRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BetPoints")]
  public partial class BetPoints : global::ProtoBuf.IExtensible
  {
    public BetPoints() {}
    
    private uint _bet_points;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bet_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_points
    {
      get { return _bet_points; }
      set { _bet_points = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomResponse")]
  public partial class EnterRoomResponse : global::ProtoBuf.IExtensible
  {
    public EnterRoomResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _owner_uuid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"owner_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner_uuid
    {
      get { return _owner_uuid; }
      set { _owner_uuid = value; }
    }
    private string _rule_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rule_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rule_name
    {
      get { return _rule_name; }
      set { _rule_name = value; }
    }
    private uint _current_round = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"current_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_round
    {
      get { return _current_round; }
      set { _current_round = value; }
    }
    private uint _all_round = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"all_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_round
    {
      get { return _all_round; }
      set { _all_round = value; }
    }
    private bool _is_seat = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_seat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_seat
    {
      get { return _is_seat; }
      set { _is_seat = value; }
    }
    private uint _seat = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _player_head_img = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"player_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_head_img
    {
      get { return _player_head_img; }
      set { _player_head_img = value; }
    }
    private string _player_nike_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"player_nike_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_nike_name
    {
      get { return _player_nike_name; }
      set { _player_nike_name = value; }
    }
    private string _user_ip = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"user_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_ip
    {
      get { return _user_ip; }
      set { _user_ip = value; }
    }
    private string _evaluate_score = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private bool _is_dismiss = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"is_dismiss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_dismiss
    {
      get { return _is_dismiss; }
      set { _is_dismiss = value; }
    }
    private string _room_rules = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"room_rules", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string room_rules
    {
      get { return _room_rules; }
      set { _room_rules = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints> _betPoints = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints>();
    [global::ProtoBuf.ProtoMember(16, Name=@"betPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints> betPoints
    {
      get { return _betPoints; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.EnterRoomResponse.Player> _player = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.EnterRoomResponse.Player>();
    [global::ProtoBuf.ProtoMember(17, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.EnterRoomResponse.Player> player
    {
      get { return _player; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private uint _seat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private bool _is_online = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_online
    {
      get { return _is_online; }
      set { _is_online = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _player_head_img = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"player_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_head_img
    {
      get { return _player_head_img; }
      set { _player_head_img = value; }
    }
    private string _player_nike_name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"player_nike_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_nike_name
    {
      get { return _player_nike_name; }
      set { _player_nike_name = value; }
    }
    private string _user_ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"user_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_ip
    {
      get { return _user_ip; }
      set { _user_ip = value; }
    }
    private string _evaluate_score = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterRoomOtherResponse")]
  public partial class EnterRoomOtherResponse : global::ProtoBuf.IExtensible
  {
    public EnterRoomOtherResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _seat = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private string _player_uuid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private bool _is_online = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"is_online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_online
    {
      get { return _is_online; }
      set { _is_online = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _player_head_img = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"player_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_head_img
    {
      get { return _player_head_img; }
      set { _player_head_img = value; }
    }
    private string _player_nike_name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"player_nike_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_nike_name
    {
      get { return _player_nike_name; }
      set { _player_nike_name = value; }
    }
    private string _user_ip = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"user_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_ip
    {
      get { return _user_ip; }
      set { _user_ip = value; }
    }
    private string _evaluate_score = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomRequest")]
  public partial class ExitRoomRequest : global::ProtoBuf.IExtensible
  {
    public ExitRoomRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomToOtherResponse")]
  public partial class ExitRoomToOtherResponse : global::ProtoBuf.IExtensible
  {
    public ExitRoomToOtherResponse() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomResultResponse")]
  public partial class ExitRoomResultResponse : global::ProtoBuf.IExtensible
  {
    public ExitRoomResultResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DismissRoomRequest")]
  public partial class DismissRoomRequest : global::ProtoBuf.IExtensible
  {
    public DismissRoomRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DismissRoomToOtherResponse")]
  public partial class DismissRoomToOtherResponse : global::ProtoBuf.IExtensible
  {
    public DismissRoomToOtherResponse() {}
    
    private string _dismiss_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dismiss_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dismiss_uuid
    {
      get { return _dismiss_uuid; }
      set { _dismiss_uuid = value; }
    }
    private uint _expire_seconds = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expire_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expire_seconds
    {
      get { return _expire_seconds; }
      set { _expire_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerVoteDismissRoomRequest")]
  public partial class PlayerVoteDismissRoomRequest : global::ProtoBuf.IExtensible
  {
    public PlayerVoteDismissRoomRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private bool _flag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerVoteDismissRoomResponse")]
  public partial class PlayerVoteDismissRoomResponse : global::ProtoBuf.IExtensible
  {
    public PlayerVoteDismissRoomResponse() {}
    
    private string _play_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"play_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string play_uuid
    {
      get { return _play_uuid; }
      set { _play_uuid = value; }
    }
    private bool _flag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DismissRoomResultResponse")]
  public partial class DismissRoomResultResponse : global::ProtoBuf.IExtensible
  {
    public DismissRoomResultResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyRequest")]
  public partial class ReadyRequest : global::ProtoBuf.IExtensible
  {
    public ReadyRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyResponse")]
  public partial class ReadyResponse : global::ProtoBuf.IExtensible
  {
    public ReadyResponse() {}
    
    private string _play_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"play_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string play_uuid
    {
      get { return _play_uuid; }
      set { _play_uuid = value; }
    }
    private uint _seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Card")]
  public partial class Card : global::ProtoBuf.IExtensible
  {
    public Card() {}
    
    private uint _card;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint card
    {
      get { return _card; }
      set { _card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectRequest")]
  public partial class ReconnectRequest : global::ProtoBuf.IExtensible
  {
    public ReconnectRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectResponse")]
  public partial class ReconnectResponse : global::ProtoBuf.IExtensible
  {
    public ReconnectResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _owner_uuid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"owner_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner_uuid
    {
      get { return _owner_uuid; }
      set { _owner_uuid = value; }
    }
    private string _rule_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rule_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rule_name
    {
      get { return _rule_name; }
      set { _rule_name = value; }
    }
    private uint _current_round = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"current_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_round
    {
      get { return _current_round; }
      set { _current_round = value; }
    }
    private uint _all_round = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"all_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_round
    {
      get { return _all_round; }
      set { _all_round = value; }
    }
    private bool _is_seat = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"is_seat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_seat
    {
      get { return _is_seat; }
      set { _is_seat = value; }
    }
    private uint _seat = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _player_head_img = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"player_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_head_img
    {
      get { return _player_head_img; }
      set { _player_head_img = value; }
    }
    private string _player_nike_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"player_nike_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_nike_name
    {
      get { return _player_nike_name; }
      set { _player_nike_name = value; }
    }
    private string _user_ip = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"user_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_ip
    {
      get { return _user_ip; }
      set { _user_ip = value; }
    }
    private string _evaluate_score = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private bool _is_dismiss = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"is_dismiss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_dismiss
    {
      get { return _is_dismiss; }
      set { _is_dismiss = value; }
    }
    private uint _rule_step = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"rule_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rule_step
    {
      get { return _rule_step; }
      set { _rule_step = value; }
    }
    private uint _rule_operation = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"rule_operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rule_operation
    {
      get { return _rule_operation; }
      set { _rule_operation = value; }
    }
    private uint _point = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> _card = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card>();
    [global::ProtoBuf.ProtoMember(18, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> card
    {
      get { return _card; }
    }
  
    private uint _remain_time = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"remain_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint remain_time
    {
      get { return _remain_time; }
      set { _remain_time = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints> _betPoints = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints>();
    [global::ProtoBuf.ProtoMember(20, Name=@"betPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.BetPoints> betPoints
    {
      get { return _betPoints; }
    }
  
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.ReconnectResponse.Player> _player = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.ReconnectResponse.Player>();
    [global::ProtoBuf.ProtoMember(21, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.ReconnectResponse.Player> player
    {
      get { return _player; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private uint _seat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private bool _is_online = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_online
    {
      get { return _is_online; }
      set { _is_online = value; }
    }
    private uint _total_score = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _player_head_img = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_head_img
    {
      get { return _player_head_img; }
      set { _player_head_img = value; }
    }
    private string _player_nike_name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"player_nike_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string player_nike_name
    {
      get { return _player_nike_name; }
      set { _player_nike_name = value; }
    }
    private string _user_ip = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"user_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_ip
    {
      get { return _user_ip; }
      set { _user_ip = value; }
    }
    private string _evaluate_score = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private bool _is_seat = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"is_seat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_seat
    {
      get { return _is_seat; }
      set { _is_seat = value; }
    }
    private bool _is_banker = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"is_banker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_banker
    {
      get { return _is_banker; }
      set { _is_banker = value; }
    }
    private uint _rule_step = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rule_step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rule_step
    {
      get { return _rule_step; }
      set { _rule_step = value; }
    }
    private uint _rule_operation = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"rule_operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rule_operation
    {
      get { return _rule_operation; }
      set { _rule_operation = value; }
    }
    private uint _point = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> _card = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card>();
    [global::ProtoBuf.ProtoMember(14, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> card
    {
      get { return _card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnlineStatusResponse")]
  public partial class OnlineStatusResponse : global::ProtoBuf.IExtensible
  {
    public OnlineStatusResponse() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private bool _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynchroniseExpressionResponse")]
  public partial class SynchroniseExpressionResponse : global::ProtoBuf.IExtensible
  {
    public SynchroniseExpressionResponse() {}
    
    private uint _expression_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"expression_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint expression_id
    {
      get { return _expression_id; }
      set { _expression_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientBetRequest")]
  public partial class ClientBetRequest : global::ProtoBuf.IExtensible
  {
    public ClientBetRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _bet_point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bet_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_point
    {
      get { return _bet_point; }
      set { _bet_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBetResponse")]
  public partial class ServerBetResponse : global::ProtoBuf.IExtensible
  {
    public ServerBetResponse() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private uint _bet_point;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bet_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_point
    {
      get { return _bet_point; }
      set { _bet_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBankerNotice1Response")]
  public partial class ServerBankerNotice1Response : global::ProtoBuf.IExtensible
  {
    public ServerBankerNotice1Response() {}
    
    private bool _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _expire_seconds = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expire_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expire_seconds
    {
      get { return _expire_seconds; }
      set { _expire_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBankerNotice2Response")]
  public partial class ServerBankerNotice2Response : global::ProtoBuf.IExtensible
  {
    public ServerBankerNotice2Response() {}
    
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> _card = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card>();
    [global::ProtoBuf.ProtoMember(1, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> card
    {
      get { return _card; }
    }
  
    private uint _expire_seconds = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expire_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expire_seconds
    {
      get { return _expire_seconds; }
      set { _expire_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientBetAgainRequest")]
  public partial class ClientBetAgainRequest : global::ProtoBuf.IExtensible
  {
    public ClientBetAgainRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _bet_point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bet_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_point
    {
      get { return _bet_point; }
      set { _bet_point = value; }
    }
    private uint _bet_all_point;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bet_all_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_all_point
    {
      get { return _bet_all_point; }
      set { _bet_all_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBetAgainResponse")]
  public partial class ServerBetAgainResponse : global::ProtoBuf.IExtensible
  {
    public ServerBetAgainResponse() {}
    
    private string _player_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_uuid
    {
      get { return _player_uuid; }
      set { _player_uuid = value; }
    }
    private uint _seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private uint _bet_point;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bet_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_point
    {
      get { return _bet_point; }
      set { _bet_point = value; }
    }
    private uint _bet_all_point;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bet_all_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bet_all_point
    {
      get { return _bet_all_point; }
      set { _bet_all_point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientBankerRequest")]
  public partial class ClientBankerRequest : global::ProtoBuf.IExtensible
  {
    public ClientBankerRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerToBankerResponse")]
  public partial class ServerToBankerResponse : global::ProtoBuf.IExtensible
  {
    public ServerToBankerResponse() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private uint _banker_seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"banker_seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint banker_seat
    {
      get { return _banker_seat; }
      set { _banker_seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBankerResponse")]
  public partial class ServerBankerResponse : global::ProtoBuf.IExtensible
  {
    public ServerBankerResponse() {}
    
    private bool _is_banker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_banker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_banker
    {
      get { return _is_banker; }
      set { _is_banker = value; }
    }
    private string _banker_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"banker_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string banker_uuid
    {
      get { return _banker_uuid; }
      set { _banker_uuid = value; }
    }
    private uint _banker_seat;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"banker_seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint banker_seat
    {
      get { return _banker_seat; }
      set { _banker_seat = value; }
    }
    private bool _is_bet;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"is_bet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_bet
    {
      get { return _is_bet; }
      set { _is_bet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerCardsResponse")]
  public partial class ServerCardsResponse : global::ProtoBuf.IExtensible
  {
    public ServerCardsResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> _card = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card>();
    [global::ProtoBuf.ProtoMember(1, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> card
    {
      get { return _card; }
    }
  
    private uint _card_result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_result
    {
      get { return _card_result; }
      set { _card_result = value; }
    }
    private uint _expire_seconds = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"expire_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expire_seconds
    {
      get { return _expire_seconds; }
      set { _expire_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynchroniseCardsRequest")]
  public partial class SynchroniseCardsRequest : global::ProtoBuf.IExtensible
  {
    public SynchroniseCardsRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynchroniseCardsResponse")]
  public partial class SynchroniseCardsResponse : global::ProtoBuf.IExtensible
  {
    public SynchroniseCardsResponse() {}
    
    private string _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player
    {
      get { return _player; }
      set { _player = value; }
    }
    private uint _seat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> _card = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card>();
    [global::ProtoBuf.ProtoMember(3, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.Card> card
    {
      get { return _card; }
    }
  
    private uint _card_face = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"card_face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_face
    {
      get { return _card_face; }
      set { _card_face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WinOrLoseResponse")]
  public partial class WinOrLoseResponse : global::ProtoBuf.IExtensible
  {
    public WinOrLoseResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.WinOrLoseResponse.Result> _result = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.WinOrLoseResponse.Result>();
    [global::ProtoBuf.ProtoMember(1, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.WinOrLoseResponse.Result> result
    {
      get { return _result; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Result")]
  public partial class Result : global::ProtoBuf.IExtensible
  {
    public Result() {}
    
    private string _from_user_uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from_user_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string from_user_uuid
    {
      get { return _from_user_uuid; }
      set { _from_user_uuid = value; }
    }
    private string _to_user_uuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"to_user_uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string to_user_uuid
    {
      get { return _to_user_uuid; }
      set { _to_user_uuid = value; }
    }
    private uint _point;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserAllResult")]
  public partial class UserAllResult : global::ProtoBuf.IExtensible
  {
    public UserAllResult() {}
    
    private readonly global::System.Collections.Generic.List<com.sansanbbox.protobuf.UserAllResult.AllResult> _allResult = new global::System.Collections.Generic.List<com.sansanbbox.protobuf.UserAllResult.AllResult>();
    [global::ProtoBuf.ProtoMember(1, Name=@"allResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.sansanbbox.protobuf.UserAllResult.AllResult> allResult
    {
      get { return _allResult; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllResult")]
  public partial class AllResult : global::ProtoBuf.IExtensible
  {
    public AllResult() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private string _nick_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private string _head_img;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string head_img
    {
      get { return _head_img; }
      set { _head_img = value; }
    }
    private uint _point;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint point
    {
      get { return _point; }
      set { _point = value; }
    }
    private uint _win_count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"win_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint win_count
    {
      get { return _win_count; }
      set { _win_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameRequest")]
  public partial class StartGameRequest : global::ProtoBuf.IExtensible
  {
    public StartGameRequest() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartGameResponse")]
  public partial class StartGameResponse : global::ProtoBuf.IExtensible
  {
    public StartGameResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _expire_seconds = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expire_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint expire_seconds
    {
      get { return _expire_seconds; }
      set { _expire_seconds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerBetOverResponse")]
  public partial class ServerBetOverResponse : global::ProtoBuf.IExtensible
  {
    public ServerBetOverResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomWebResponse")]
  public partial class CreateRoomWebResponse : global::ProtoBuf.IExtensible
  {
    public CreateRoomWebResponse() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}