//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: user.proto
namespace com.sansanbbox.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private string _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private string _user_nick_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_nick_name
    {
      get { return _user_nick_name; }
      set { _user_nick_name = value; }
    }
    private string _user_head_img = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_head_img", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_head_img
    {
      get { return _user_head_img; }
      set { _user_head_img = value; }
    }
    private uint _account_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private string _login_ip = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"login_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string login_ip
    {
      get { return _login_ip; }
      set { _login_ip = value; }
    }
    private string _play_count = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"play_count", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string play_count
    {
      get { return _play_count; }
      set { _play_count = value; }
    }
    private string _register_time = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"register_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string register_time
    {
      get { return _register_time; }
      set { _register_time = value; }
    }
    private uint _is_enter_room = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"is_enter_room", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_enter_room
    {
      get { return _is_enter_room; }
      set { _is_enter_room = value; }
    }
    private double _evaluate_score = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"evaluate_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double evaluate_score
    {
      get { return _evaluate_score; }
      set { _evaluate_score = value; }
    }
    private uint _user_diamond = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"user_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint user_diamond
    {
      get { return _user_diamond; }
      set { _user_diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}